0.132 (patches unapplied)
Imported using git-ubuntu import.

diff --git a/hook-functions b/hook-functions
--- a/hook-functions
+++ b/hook-functions
@@ -91,9 +91,9 @@ manual_add_modules()
 				fi
 
 				kmod_modname="${kmod##*/}"
-				kmod_modname="${kmod_modname%.ko}"
+				kmod_modname="${kmod_modname%%.*}"
 				if grep -q "^$kmod_modname\\>" /proc/modules "${CONFDIR}/modules"; then
-					echo "W: Possible missing firmware /lib/firmware/${firmware} for module $(basename ${kmod} .ko)" >&2
+					echo "W: Possible missing firmware /lib/firmware/${firmware} for module ${kmod_modname}" >&2
 				fi
 				continue
 			fi
@@ -197,7 +197,7 @@ copy_exec() {
 # Copy entire subtrees to the initramfs
 copy_modules_dir()
 {
-	local kmod exclude
+	local kmod first exclude
 	local modules=
 	local dir="$1"
 	shift
@@ -211,12 +211,21 @@ copy_modules_dir()
 			echo "(excluding $*)"
 		fi
 	fi
-	while [ $# -ge 1 ]; do
-		exclude="${exclude:-} -name $1 -prune -o "
-		shift
+
+	# Build up an expression for find
+	first=true
+	for exclude in "$@"; do
+		# Change .ko suffix in exclusion to .ko*
+		if [ "${exclude%.ko}" != "${exclude}" ]; then
+			exclude="${exclude}*"
+		fi
+		$first && set --
+		set -- "$@" -name "${exclude}" -prune -o
+		first=false
 	done
-	for kmod in $(find "${MODULESDIR}/${dir}" ${exclude:-} -name '*.ko' -printf '%f\n'); do
-		modules="$modules ${kmod%.ko}"
+
+	for kmod in $(find "${MODULESDIR}/${dir}" "$@" -name '*.ko*' -printf '%f\n'); do
+		modules="$modules ${kmod%%.*}"
 	done
 	manual_add_modules $modules
 }
@@ -610,11 +619,11 @@ hidden_dep_add_modules()
 	manual_add_modules $(
 		{
 			cat "${DESTDIR}/lib/modules/${version}/modules.builtin"
-			find "${DESTDIR}/lib/modules/${version}/kernel" -name '*.ko'
+			find "${DESTDIR}/lib/modules/${version}/kernel" -name '*.ko*'
 		} |
 		while read module; do
 			module="${module##*/}"
-			module="${module%.ko}"
+			module="${module%%.*}"
 			case "$module" in
 			libcrc32c)
 				echo crc32c
