0.97 (patches unapplied)
Imported using git-ubuntu import.

diff --git a/hook-functions b/hook-functions
--- a/hook-functions
+++ b/hook-functions
@@ -3,7 +3,7 @@
 catenate_cpiogz() {
 	# Sanity check
 	if [ ! -e "${1}" ]; then
-		echo "W:catenate_cpiogz: arg1='${1}' does not exist." >&2
+		echo "W: catenate_cpiogz: arg1='${1}' does not exist." >&2
 		return
 	fi
 
@@ -29,7 +29,7 @@ add_modules_from_file()
 {
 	# Sanity check
 	if [ ! -e "${1}" ]; then
-		echo "W:add_modules_from_file: arg1='${1}' does not exist." >&2
+		echo "W: add_modules_from_file: arg1='${1}' does not exist." >&2
 		return
 	fi
 
@@ -72,7 +72,7 @@ manual_add_modules()
 				# /proc/modules exists
 				if [ ! -e /proc/modules ] ; then
 					continue
-                                fi
+				fi
 
 				if grep -q "^$(basename "${kmod}" .ko)[[:space:]]" \
 				/proc/modules \
@@ -127,10 +127,10 @@ copy_exec() {
 
 	# Copy the dependant libraries
 	for x in $(ldd ${src} 2>/dev/null | sed -e '
-	    /\//!d;
-	    /linux-gate/d;
-	    /=>/ {s/.*=>[[:blank:]]*\([^[:blank:]]*\).*/\1/};
-	    s/[[:blank:]]*\([^[:blank:]]*\) (.*)/\1/' 2>/dev/null); do
+		/\//!d;
+		/linux-gate/d;
+		/=>/ {s/.*=>[[:blank:]]*\([^[:blank:]]*\).*/\1/};
+		s/[[:blank:]]*\([^[:blank:]]*\) (.*)/\1/' 2>/dev/null); do
 
 		# Try to use non-optimised libraries where possible.
 		# We assume that all HWCAP libraries will be in tls,
@@ -166,7 +166,7 @@ copy_modules_dir()
 	if [ "${verbose}" = "y" ]; then
 		echo "Copying module directory ${dir}"
 		if [ $# -ge 1 ]; then
-		    echo "(excluding $*)"
+			echo "(excluding $*)"
 		fi
 	fi
 	while [ $# -ge 1 ]; do
@@ -183,7 +183,7 @@ sys_walk_mod_add()
 {
 	local driver_path module
 	device_path="$1"
-	
+
 	while [ "${device_path}" != "/sys" ]; do
 		sys_walk_modalias ${device_path}
 		driver_path="$(readlink -f ${device_path}/driver/module)"
@@ -220,17 +220,27 @@ dep_add_modules()
 
 	# require mounted sysfs
 	if [ ! -d /sys/devices/ ]; then
-		echo "mkinitramfs: MODULES dep requires mounted sysfs on /sys"
+		echo "mkinitramfs: MODULES dep requires mounted sysfs on /sys" >&2
 		exit 1
 	fi
 
 	# findout root block device + fstype
 	eval "$(mount | awk '/\/dev\// {if ($3 == "/") {print "root=" $1 "\nFSTYPE=" $5; exit}}')"
+	if [ -z "$root" ]; then
+		echo "mkinitramfs: failed to determine root device" >&2
+		echo "mkinitramfs: workaround is MODULES=most" >&2
+		echo "Error please report bug on initramfs-tools and include the output of 'mount'" >&2
+		exit 1
+	fi
 
 	# handle ubifs and return since ubifs root is a char device but
 	# most of the commands below only work with block devices.
 	if [ "${FSTYPE}" = "ubifs" ]; then
 		manual_add_modules "${FSTYPE}"
+		# add some modules required by ubifs on which it doesn's depend
+		manual_add_modules deflate
+		manual_add_modules zlib
+		manual_add_modules lzo
 		return
 	fi
 
@@ -246,10 +256,10 @@ dep_add_modules()
 	if [ "${FSTYPE}" = "unknown" ]; then
 		FSTYPE=$(blkid -o value -s TYPE "${root}")
 		if [  -z "${FSTYPE}" ]; then
-			echo "mkinitramfs: unknown fstype on root ${root}"
-			echo "mkinitramfs: workaround is MODULES=most" 
-			echo "Error please report bug on initramfs-tools" 
-		exit 1
+			echo "mkinitramfs: unknown fstype on root ${root}" >&2
+			echo "mkinitramfs: workaround is MODULES=most" >&2
+			echo "Error please report bug on initramfs-tools" >&2
+			exit 1
 		fi
 	fi
 
@@ -267,9 +277,7 @@ dep_add_modules()
 		done
 		# lvm on md or luks on md
 		if [ "${block#md}" != "${block}" ]; then
-			block=$(grep "^${block}" /proc/mdstat | \
-			        awk "{gsub(/^${block} : .* (multipath|linear|raid[[:digit:]]+)\ /,\"\")};1")
-			block="${block%%\[*}"
+			block=$(sed -ne 's/multipath/[/' -e 's/linear/[/' -e 's/raid[0-9][0-9]*/[/' -e 's/\([hs]d[a-z][a-z]*\)[0-9][0-9]*/\1/g' -e '/^'${block}' :/s/^[^[]*\[ \([^\[]*\)\[.*$/\1/p' </proc/mdstat)
 		fi
 		# luks or lvm on cciss or ida
 		if [ "${block#cciss}" != "${block}" ] \
@@ -281,28 +289,15 @@ dep_add_modules()
 	# md root new naming scheme /dev/md/X
 	elif [ "${root#/dev/md/}" != "${root}" ]; then
 		root=${root#/dev/md/}
-		block=$(grep "^md${root}" /proc/mdstat | \
-			awk "{gsub(/^md${root} : .* (multipath|linear|raid[[:digit:]]+)\ /,\"\")};1")
-		block="${block%%\[*}"
 		# drop the partition number only for sdX and hdX devices
 		# and keep it for other devices like loop#, dm-# devices
-		case "$block" in
-			sd*) block=${block%%[0-9]*};;
-			hd*) block=${block%%[0-9]*};;
-		esac
+		block=$(sed -ne 's/multipath/[/' -e 's/linear/[/' -e 's/raid[0-9][0-9]*/[/' -e 's/\([hs]d[a-z][a-z]*\)[0-9][0-9]*/\1/g' -e '/^md'$root' :/s/^[^[]*\[ \([^\[]*\)\[.*$/\1/p' </proc/mdstat)
 	# md root /dev/mdX
 	elif [ "${root#/dev/md}" != "${root}" ]; then
 		root=${root#/dev/md}
-		block=$(grep "^md${root}" /proc/mdstat | \
-			awk "{gsub(/^md${root} : .* (multipath|linear|raid[[:digit:]]+)\ /,\"\")};1")
-		block="${block%%\[*}"
 		# drop the partition number only for sdX and hdX devices
 		# and keep it for other devices like loop#, dm-# devices
-		case "$block" in
-			sd*) block=${block%%[0-9]*};;
-			hd*) block=${block%%[0-9]*};;
-		esac
-
+		block=$(sed -ne 's/multipath/[/' -e 's/linear/[/' -e 's/raid[0-9][0-9]*/[/' -e 's/\([hs]d[a-z][a-z]*\)[0-9][0-9]*/\1/g' -e '/^md'$root' :/s/^[^[]*\[ \([^\[]*\)\[.*$/\1/p' </proc/mdstat)
 	# cciss device
 	elif [ "${root#/dev/cciss/}" != "${root}" ]; then
 		block=${root#/dev/cciss/*}
@@ -343,9 +338,9 @@ dep_add_modules()
 
 	# Error out if /sys lack block dev
 	if [ -z "${block}" ] || [ ! -e /sys/block/${block} ]; then
-		echo "mkinitramfs: for root ${root} missing ${block} /sys/block/ entry"
-		echo "mkinitramfs: workaround is MODULES=most" 
-		echo "mkinitramfs: Error please report the bug" 
+		echo "mkinitramfs: for root ${root} missing ${block} /sys/block/ entry" >&2
+		echo "mkinitramfs: workaround is MODULES=most" >&2
+		echo "mkinitramfs: Error please report the bug" >&2
 		exit 1
 	fi
 
@@ -368,6 +363,10 @@ dep_add_modules()
 
 	if [ -e /sys/bus/mmc/devices/ ]; then
 		manual_add_modules mmc_block
+	fi
+
+	if [ -e /sys/bus/virtio ] ; then
+		manual_add_modules virtio_pci
 	fi
 
 	if [ -e /sys/bus/i2o/devices/ ]; then
@@ -423,6 +422,11 @@ auto_add_modules()
 	;;
 	block)
 		copy_modules_dir kernel/drivers/block
+	;;
+	ubi)
+		for x in deflate zlib lzo ubi ubifs; do
+			manual_add_modules "${x}"
+		done
 	;;
 	ieee1394)
 		for x in ohci1394 sbp2; do
@@ -525,8 +529,8 @@ check_minkver()
 	fi
 	set_initlist
 	for cm_x in ${initlist:-}; do
-		# sed: keep last line starting with MINKVER=,
-		#      remove MINKVER= and trailing space
+		# sed:  keep last line starting with MINKVER=,
+		#	remove MINKVER= and trailing space
 		minver=$(sed '/^MINKVER=/!d;$!d;s/^MINKVER=//;s/[[:space:]]*$//' "${initdir}/${cm_x}")
 		if [ -z "${tmp}" ]; then
 			continue
