0.92bubuntu54 (patches unapplied)
Imported using git-ubuntu import.

diff --git a/hook-functions b/hook-functions
--- a/hook-functions
+++ b/hook-functions
@@ -69,23 +69,29 @@ manual_add_modules()
 			continue
 		fi
 		for firmware in $firmwares; do
-			if [ -e "${DESTDIR}/lib/firmware/${version}/${firmware}" ]; then
+			if [ -e "${DESTDIR}/lib/firmware/${firmware}" ] \
+			|| [ -e "${DESTDIR}/lib/firmware/${version}/${firmware}" ]; then
 				continue
 			fi
 
 			# Only print warning for missing fw of loaded module
 			# or forced loaded module
-			if [ ! -e "/lib/firmware/${version}/${firmware}" ]; then
-				if grep -q "^$(basename "${mam_x}" .ko)" \
+			if [ ! -e "/lib/firmware/${firmware}" ] \
+			&& [ ! -e "/lib/firmware/${version}/${firmware}" ]; then
+				if grep -q "^$(basename "${mam_x}" .ko)[[:space:]]" \
 				/proc/modules \
 				|| grep -q "^$(basename "${mam_x}" .ko)" \
 				"${CONFDIR}/modules"; then
-					echo "W: Possible missing firmware /lib/firmware/${version}/${firmware} for module $(basename ${mam_x} .ko)" >&2
+					echo "W: Possible missing firmware /lib/firmware/${firmware} for module $(basename ${mam_x} .ko)" >&2
 				fi
 				continue
 			fi
 
-			copy_exec "/lib/firmware/${version}/${firmware}"
+			if [ -e "/lib/firmware/${version}/${firmware}" ]; then
+				copy_exec "/lib/firmware/${version}/${firmware}"
+			else
+				copy_exec "/lib/firmware/${firmware}"
+			fi
 			if [ "${verbose}" = "y" ]; then
 				echo "Adding firmware ${firmware}"
 			fi
