0.69ubuntu1 (patches unapplied)
Imported using git-ubuntu import.

diff --git a/mkinitramfs b/mkinitramfs
--- a/mkinitramfs
+++ b/mkinitramfs
@@ -4,53 +4,79 @@ umask 0022
 
 # Defaults
 keep="n"
-CONFDIR="/etc/mkinitramfs"
+CONFDIR="/etc/initramfs-tools"
 verbose="n"
 errors_to="2>/dev/null"
+BUSYBOXDIR="/usr/lib/initramfs-tools/bin/"
+# BUSYBOXDIR="/bin"
 
-while getopts "d:ko:r:" flag; do
-	case $flag in
-	d)
-		CONFDIR="${OPTARG}"
+OPTIONS=`getopt -o d:ko:r:v -n "$0" -- "$@"`
+
+# Check for non-GNU getopt
+if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi
+
+eval set -- "$OPTIONS"
+
+while true; do
+	case "$1" in
+	-d)
+		CONFDIR="$2"
+		shift 2
 		if [ ! -d "${CONFDIR}" ]; then
 			echo "${0}: ${CONFDIR}: Not a directory" >&2
 			exit 1
 		fi
 		;;
-	o)
-		touch ${OPTARG}
-		outfile="$(readlink -f ${OPTARG})"
+	-o)
+		touch $2
+		outfile="$(readlink -f "$2")"
+		shift 2
 		;;
-	k)
+	-k)
 		keep="y"
+		shift
+		;;
+	-r)
+		ROOT="$2"
+		shift 2
+		;;
+	-v)
+		verbose="y"
+		shift
+		;;
+	--)
+		shift
+		break
+		;;
+	*)
+		echo "Internal error!" >&2
+		exit 1
 		;;
 	esac
 done
-
-shift $((${OPTIND} - 1))
 
 # For dependency ordered mkinitramfs hook scripts.
 . /usr/share/initramfs-tools/scripts/functions
 . /usr/share/initramfs-tools/hook-functions
 
-. ${CONFDIR}/initramfs.conf
+. "${CONFDIR}/initramfs.conf"
 EXTRA_CONF=''
-for i in ${CONFDIR}/conf.d/*; do
+for i in ${CONFDIR}/conf.d/* /usr/share/initramfs-tools/conf.d/*; do
 	EXTRA_CONF="${EXTRA_CONF} $(basename $i | grep '^[a-z0-9][a-z0-9\._-]*$' | grep -v '\.dpkg-.*$')";
 done
 for i in ${EXTRA_CONF}; do
 . ${CONFDIR}/conf.d/${i}
 done
 
-if [ x${outfile} = x ]; then
+if [ -z "${outfile}" ]; then
 	usage
 fi
 
 # And by "version" we really mean path to kernel modules
 # This is braindead, and exists to preserve the interface with mkinitrd
 if [ ${#} -ne 1 ]; then
-	version=$(uname -r)
-else 
+	version="$(uname -r)"
+else
 	version="${1}"
 fi
 
@@ -60,36 +86,39 @@ check_minkver ${version}
 check_minkver ${version} /usr/share/initramfs-tools/hooks
 check_minkver ${version} ${CONFDIR}/hooks
 
-case ${version} in
+case "${version}" in
 /lib/modules/*/[!/]*)
         ;;
 /lib/modules/[!/]*)
-        version=${version#/lib/modules/}
-        version=${version%%/*}
+        version="${version#/lib/modules/}"
+        version="${version%%/*}"
         ;;
 esac
 
-case ${version} in
+case "${version}" in
 */*)
-        echo $PROG: ${version} is not a valid kernel version >&2
+        echo "$PROG: ${version} is not a valid kernel version" >&2
         exit 1
         ;;
 esac
 
-if [ -d ${outfile} ]; then
+if [ -d "${outfile}" ]; then
 	echo "${outfile} is a directory"
 	exit 1
 fi
 
 MODULESDIR="/lib/modules/${version}"
 
-if [ ! -e ${MODULESDIR} ]; then
+if [ ! -e "${MODULESDIR}" ]; then
 	echo "Cannot find ${MODULESDIR}"
 	exit 1
 fi
+if [ ! -e "${MODULESDIR}/modules.depmod" ]; then
+	depmod ${version}
+fi
 
-DESTDIR=$(mktemp -t -d mkinitramfs_XXXXXX) || exit 1
-__TMPCPIOGZ=$(mktemp -t mkinitramfs-OL_XXXXXX) || exit 1
+DESTDIR="$(mktemp -t -d mkinitramfs_XXXXXX)" || exit 1
+__TMPCPIOGZ="$(mktemp -t mkinitramfs-OL_XXXXXX)" || exit 1
 
 DPKG_ARCH=`dpkg --print-installation-architecture`
 
@@ -100,18 +129,19 @@ export version
 export CONFDIR
 export DESTDIR
 export DPKG_ARCH
+export verbose
 
 # Private, used by 'catenate_cpiogz'.
 export __TMPCPIOGZ
 
 for d in bin conf/conf.d etc lib modules sbin scripts; do
-    mkdir -p ${DESTDIR}/${d}
+    mkdir -p "${DESTDIR}/${d}"
 done
 
 # MODULES=list case.  Always honour.
-for x in ${CONFDIR}/modules /usr/share/initramfs-tools/modules.d/*; do
+for x in "${CONFDIR}/modules" /usr/share/initramfs-tools/modules.d/*; do
 	if [ -f "${x}" ]; then
-		add_modules_from_file ${x}
+		add_modules_from_file "${x}"
 	fi
 done
 
@@ -134,61 +164,49 @@ fi
 ln -s /usr/lib/klibc/bin/* ${DESTDIR}/bin
 ln -s /lib/klibc-*.so ${DESTDIR}/lib
 copy_exec /usr/share/initramfs-tools/init /init
-cp -a /usr/share/initramfs-tools/scripts/* ${DESTDIR}/scripts
+cp -a /usr/share/initramfs-tools/scripts/* "${DESTDIR}/scripts"
 for f in $(cd ${CONFDIR}/scripts && \
 	find . \( -name '*.dpkg*' -prune -o -name '*~' -prune \) \
 		-o -type f -print); do
-	mkdir --parents ${DESTDIR}/scripts/$(dirname ${f})
-cp -p ${CONFDIR}/scripts/${f} ${DESTDIR}/scripts/$(dirname ${f})
+	mkdir --parents "${DESTDIR}/scripts/$(dirname "${f}")"
+cp -p "${CONFDIR}/scripts/${f}" "${DESTDIR}/scripts/$(dirname "${f}")"
 done
 echo "DPKG_ARCH=${DPKG_ARCH}" > ${DESTDIR}/conf/arch.conf
-copy_exec ${CONFDIR}/initramfs.conf /conf
+copy_exec "${CONFDIR}/initramfs.conf" /conf
 for i in ${EXTRA_CONF}; do
-	copy_exec ${CONFDIR}/conf.d/${i} /conf/conf.d
+	copy_exec "${CONFDIR}/conf.d/${i}" /conf/conf.d
 done
+echo "ROOT=${ROOT}" > ${DESTDIR}/conf/conf.d/root
 
 # Busybox
-rm -f ${DESTDIR}/bin/sh
-ln -s /usr/lib/initramfs-tools/bin/busybox ${DESTDIR}/bin/sh
-# This is ugly, but needed atm to make the builtins work =(
-ln -s /usr/lib/initramfs-tools/bin/busybox ${DESTDIR}/bin/busybox
+if [ "x${BUSYBOX}" = "xn" ]; then
+	ln -s ${DESTDIR}/bin/sh.shared ${DESTDIR}/bin/sh
+	echo "Warning: Busybox is required for successful boot!"
+else
+	rm -f ${DESTDIR}/bin/sh
+	copy_exec ${BUSYBOXDIR}/busybox /bin/busybox
+	ln -s ${BUSYBOXDIR}/busybox ${DESTDIR}/bin/sh
+fi
 
 # Modutils
 copy_exec /sbin/modprobe /sbin
 copy_exec /sbin/depmod /sbin
 copy_exec /sbin/rmmod /sbin
-mkdir -p ${DESTDIR}/etc/modprobe.d
-cp -a /etc/modprobe.d/* ${DESTDIR}/etc/modprobe.d
-
-# FIXME: Remove this Raid block after Dapper releases
-if [ -x /sbin/mdadm -a -x /sbin/mdrun -a ! -f /usr/share/initramfs-tools/hooks/md ]; then
-	copy_exec /sbin/mdadm /sbin
-	copy_exec /sbin/mdrun /sbin
-	for x in md linear raid0 raid1 raid5 raid6 raid10; do
-		manual_add_modules ${x}
-	done
-fi
-
-# FIXME: Remove this LVM block after Dapper releases
-if [ -x /sbin/vgchange -a -d /lib/lvm-200 -a ! -f /usr/share/initramfs-tools/hooks/lvm ]; then
-	copy_exec /lib/lvm-200/vgchange /sbin
-	for x in dm_mod dm_snapshot; do
-		manual_add_modules ${x}
-	done
-fi
+mkdir -p "${DESTDIR}/etc/modprobe.d"
+cp -a /etc/modprobe.d/* "${DESTDIR}/etc/modprobe.d"
 
 run_scripts /usr/share/initramfs-tools/hooks
-run_scripts ${CONFDIR}/hooks
+run_scripts "${CONFDIR}"/hooks
 
 # Apply DSDT to initramfs
-if [ -e ${CONFDIR}/DSDT.aml ]; then
-	copy_exec ${CONFDIR}/DSDT.aml /
+if [ -e "${CONFDIR}/DSDT.aml" ]; then
+	copy_exec "${CONFDIR}/DSDT.aml" /
 fi
 
-(cd ${DESTDIR} && find . | cpio --quiet --dereference -o -H newc | gzip -9 >${outfile})
+(cd "${DESTDIR}" && find . | cpio --quiet --dereference -o -H newc | gzip -9 >"${outfile}") || exit 1
 
-if [ -s ${__TMPCPIOGZ} ]; then
-    cat ${__TMPCPIOGZ} >>${outfile}
+if [ -s "${__TMPCPIOGZ}" ]; then
+    cat "${__TMPCPIOGZ}" >>"${outfile}" || exit 1
 fi
 
 if [ "${keep}" = "y" ]; then
diff --git a/update-initramfs b/update-initramfs
--- a/update-initramfs
+++ b/update-initramfs
@@ -14,11 +14,12 @@ usage()
 Usage: ${0} [OPTION]...
 
 Options:
- -k [version]	Specify kernel version or ALL
+ -k [version]	Specify kernel version or all
  -c		Create a new initramfs
  -u		Update an existing initramfs
  -d		Remove an existing initramfs
  -t		Take over a custom initramfs with this one
+ -b		Set alternate boot directory
  -v		Be verbose
  -h		This message
 
@@ -62,8 +63,12 @@ set_initramfs()
 
 generate_initramfs()
 {
-	verbose "Generating ${initramfs}"
-	if mkinitramfs -o ${initramfs} ${version}; then
+	echo "update-initramfs: Generating ${initramfs}"
+	OPTS="-o"
+	if [ "${verbose}" = 1 ]; then
+		OPTS="-v $OPTS"
+	fi
+	if mkinitramfs "${OPTS}" "${initramfs}" "${version}"; then
 		set_sha1
 	else
 		mkinitramfs_return="$?"
@@ -76,32 +81,52 @@ generate_initramfs()
 	fi
 }
 
+# only run lilo if no grub is around
+run_bootloader()
+{
+	if [ -x /sbin/grub -o -e /boot/grub/menu.lst ]; then
+		if [ -e /etc/lilo.conf ]; then
+			echo
+			echo "WARNING: grub and lilo installed."
+			echo "If you use grub as bootloader everything is fine."
+			echo "If you use lilo as bootloader you must run lilo!"
+			echo
+		fi
+		return 0
+	fi
+	if [ -e /etc/lilo.conf ]; then
+		lilo -t > /dev/null
+		if [ $? -eq 0 ]; then
+			lilo
+		fi
+	fi
+}
+
 compare_sha1()
 {
-	sha1sum ${initramfs} | diff ${STATEDIR}/${version} - >/dev/null 2>&1
+	sha1sum "${initramfs}" | diff "${STATEDIR}/${version}" - >/dev/null 2>&1
 	return $?
 }
 
 # Note that this must overwrite so that updates work.
 set_sha1()
 {
-	sha1sum ${initramfs} > ${STATEDIR}/${version}
+	sha1sum "${initramfs}" > "${STATEDIR}/${version}"
 }
 
 delete_sha1()
 {
-	rm -f ${STATEDIR}/${version}
+	rm -f "${STATEDIR}/${version}"
 }
 
 get_sorted_versions()
 {
 	version_list=""
 
-	for gsv_x in ${STATEDIR}/*; do
-		gsv_x=$(basename ${gsv_x})
+	for gsv_x in "${STATEDIR}"/*; do
+		gsv_x="$(basename "${gsv_x}")"
 		if [ "${gsv_x}" = '*' ]; then
-			verbose "Nothing to do, exiting."
-			exit 0
+			return 0
 		fi
 		worklist=""
 		for gsv_i in $version_list; do
@@ -115,7 +140,7 @@ get_sorted_versions()
 		if [ "${gsv_x}" != "" ]; then
 			worklist="${worklist} ${gsv_x}"
 		fi
-		version_list=${worklist}
+		version_list="${worklist}"
 	done
 
 	verbose "Available versions: ${version_list}"
@@ -123,7 +148,7 @@ get_sorted_versions()
 
 set_current_version()
 {
-	if [ -f /boot/vmlinu?-`uname -r` ]; then
+	if [ -f /boot/initrd.img-`uname -r` ]; then
 		version=`uname -r`
 	fi
 }
@@ -131,11 +156,11 @@ set_current_version()
 set_linked_version()
 {
 	if [ -L /initrd.img ]; then
-		linktarget=$(basename $(readlink /initrd.img))
+		linktarget="$(basename "$(readlink /initrd.img)")"
 	fi
 
 	if [ -L /boot/initrd.img ]; then
-		linktarget=$(basename $(readlink /boot/initrd.img))
+		linktarget="$(basename "$(readlink /boot/initrd.img)")"
 	fi
 
 	if [ -z "${linktarget}" ]; then
@@ -161,11 +186,11 @@ create()
 	set_initramfs
 
 	if [ "${takeover}" = 0 ]; then
-		if version_exists ${version}; then
+		if version_exists "${version}"; then
 			panic "Cannot create version ${version}: already exists"
 		fi
 	
-		if [ -e ${initramfs} ]; then
+		if [ -e "${initramfs}" ]; then
 			panic "${initramfs} already exists, cannot create."
 		fi
 	fi
@@ -187,16 +212,25 @@ update()
 		set_current_version
 	fi
 
+	if [ -z "${version}" ]; then
+		verbose "Nothing to do, exiting."
+		exit 0
+	fi
+
 	if [ "${version}" = "all" ]; then
 		: FIXME check for --yes, and if not ask are you sure
 		get_sorted_versions
+		if [ -z "${version_list}" ]; then
+			verbose "Nothing to do, exiting."
+			exit 0
+		fi
 		for u_version in ${version_list}; do
 			if [ "${verbose}" = "1" ]; then
 				vflag="-v"
 			fi
 			# Don't stop if one version doesn't work.
 			set +e
-			${0} ${vflag} -u -k ${u_version}
+			"${0}" -u -k "${u_version}" ${vflag}
 			set -e
 		done
 		exit 0
@@ -208,6 +242,8 @@ update()
 
 	generate_initramfs
 
+	run_bootloader
+
 }
 
 delete()
@@ -218,11 +254,11 @@ delete()
 
 	set_initramfs
 
-	if [ ! -e ${initramfs} ]; then
+	if [ ! -e "${initramfs}" ]; then
 		panic "Cannot delete ${initramfs}, doesn't exist."
 	fi
 	
-	if ! version_exists ${version}; then
+	if ! version_exists "${version}"; then
 		panic "Cannot delete version ${version}: Not created by this utility."
 	fi
 
@@ -252,7 +288,7 @@ takeover=1
 
 ##
 
-while getopts "k:cudyvht" flag; do
+while getopts "k:cudyvtb:h?" flag; do
 	case "${flag}" in
 	k)
 		version="${OPTARG}"	
@@ -275,7 +311,14 @@ while getopts "k:cudyvht" flag; do
 	t)
 		takeover="1"
 		;;
-	h)
+	b)
+		BOOTDIR="${OPTARG}"
+		if [ ! -d "${BOOTDIR}" ]; then
+			echo "Error: ${BOOTDIR} is not a directory."
+			exit 1
+		fi
+		;;
+	h|?)
 		usage
 		;;
 	esac
