0.103ubuntu4.10 (patches unapplied)
Imported using git-ubuntu import.

diff --git a/mkinitramfs b/mkinitramfs
--- a/mkinitramfs
+++ b/mkinitramfs
@@ -165,6 +165,22 @@ if [ ! -e "${MODULESDIR}/modules.dep" ]; then
 	depmod ${version}
 fi
 
+# Prepare to clean up temporary files on exit
+DESTDIR=
+__TMPCPIOGZ=
+__TMPEARLYCPIO=
+clean_on_exit() {
+	if [ "${keep}" = "y" ]; then
+		echo "Working files in ${DESTDIR:-<not yet created>}, early initramfs in ${__TMPEARLYCPIO:-<not yet created>} and overlay in ${__TMPCPIOGZ:-<not yet created>}"
+	else
+		for path in "${DESTDIR}" "${__TMPCPIOGZ}" "${__TMPEARLYCPIO}"; do
+			test -z "${path}" || rm -rf "${path}"
+		done
+	fi
+}
+trap clean_on_exit EXIT
+trap "exit 1" INT TERM	# makes the EXIT trap effective even when killed
+
 DESTDIR="$(mktemp -d ${TMPDIR:-/tmp}/mkinitramfs_XXXXXX)" || exit 1
 chmod 755 "${DESTDIR}"
 
@@ -386,14 +402,6 @@ fi
 
 if [ -s "${__TMPCPIOGZ}" ]; then
 	cat "${__TMPCPIOGZ}" >>"${outfile}" || exit 1
-fi
-
-if [ "${keep}" = "y" ]; then
-	echo "Working files in ${DESTDIR}, early initramfs in ${__TMPEARLYCPIO} and overlay in ${__TMPCPIOGZ}"
-else
-	rm -rf "${DESTDIR}"
-	rm -rf "${__TMPCPIOGZ}"
-	rm -rf "${__TMPEARLYCPIO}"
 fi
 
 exit 0
