0.92j (patches unapplied)
Imported using git-ubuntu import.

diff --git a/update-initramfs b/update-initramfs
--- a/update-initramfs
+++ b/update-initramfs
@@ -2,8 +2,27 @@
 
 STATEDIR=/var/lib/initramfs-tools
 BOOTDIR=/boot
+CONF=/etc/initramfs-tools/update-initramfs.conf
+KPKGCONF=/etc/kernel-img.conf
+USETRIGGERS=true
+mode=""
+version=""
 
 set -e
+
+[ -r ${CONF} ] && . ${CONF}
+
+if	   $USETRIGGERS						\
+	&& [ x"$DPKG_MAINTSCRIPT_PACKAGE" != x ]		\
+	&& [ $# = 1 ]	 					\
+	&& [ x"$1" = x-u ]					\
+	&& dpkg-trigger --check-supported 2>/dev/null
+then
+	if dpkg-trigger --no-await update-initramfs; then
+		echo "update-initramfs: deferring update (trigger activated)"
+		exit 0
+	fi
+fi
 
 usage()
 {
@@ -14,7 +33,7 @@ usage()
 Usage: ${0} [OPTION]...
 
 Options:
- -k [version]	Specify kernel version or all
+ -k [version]	Specify kernel version or 'all'
  -c		Create a new initramfs
  -u		Update an existing initramfs
  -d		Remove an existing initramfs
@@ -25,6 +44,19 @@ Options:
 
 EOF
 	exit 1
+}
+
+# chroot check
+chrooted()
+{
+        # borrowed from udev's postinst
+        if [ "$(stat -c %d/%i /)" = "$(stat -Lc %d/%i /proc/1/root 2>/dev/null)" ]; then
+                # the devicenumber/inode pair of / is the same as that of
+                # /sbin/init's root, so we're *not* in a chroot and hence
+                # return false.
+                return 1
+        fi
+        return 0
 }
 
 mild_panic()
@@ -52,7 +84,7 @@ verbose()
 
 version_exists()
 {
-	[ -e "${STATEDIR}/${1}" ]
+	[ -e "${STATEDIR}/${1}" ] && [ -e "${initramfs}" ]
 	return $?
 }
 
@@ -61,44 +93,180 @@ set_initramfs()
 	initramfs="${BOOTDIR}/initrd.img-${version}"
 }
 
+
+# backup initramfs while running
+backup_initramfs()
+{
+	[ ! -r "${initramfs}" ] && return 0
+	initramfs_bak="${initramfs}.dpkg-bak"
+	[ -r "${initramfs_bak}" ] && rm -f "${initramfs_bak}"
+	ln -f "${initramfs}" "${initramfs_bak}" \
+		|| cp -a "${initramfs}" "${initramfs_bak}"
+	verbose "Keeping ${initramfs_bak}"
+}
+
+# keep booted initramfs
+backup_booted_initramfs()
+{
+	initramfs_bak="${initramfs}.dpkg-bak"
+
+	# first time run thus no backup
+	[ ! -r "${initramfs_bak}" ] && return 0
+
+	# chroot with no /proc
+	[ ! -r /proc/uptime ] && rm -f "${initramfs_bak}" && return 0
+
+	# no kept backup wanted
+	[ "${backup_initramfs}" = "no" ] && rm -f "${initramfs_bak}" && return 0
+
+	# no backup yet
+	if [ ! -r "${initramfs}.bak" ]; then
+		mv -f ${initramfs_bak} "${initramfs}.bak"
+		verbose "Backup ${initramfs}.bak"
+		return 0
+	fi
+
+	# keep booted initramfs
+	uptime_days=$(awk '{printf "%d", $1 / 3600 / 24}' /proc/uptime)
+	if [ -n "$uptime_days" ]; then
+		boot_initramfs=$(find "${initramfs}.bak" -mtime +${uptime_days})
+	fi
+	if [ -n "${boot_initramfs}" ]; then
+		mv -f "${initramfs_bak}" "${initramfs}.bak"
+		verbose "Backup ${initramfs}.bak"
+		return 0
+	fi
+	verbose "Removing current backup ${initramfs_bak}"
+	rm -f ${initramfs_bak}
+}
+
+# nuke generated copy
+remove_initramfs()
+{
+	[ -z "${initramfs_bak}" ] && return 0
+	rm -f "${initramfs_bak}"
+	verbose "Removing ${initramfs_bak}"
+}
+
+
 generate_initramfs()
 {
 	echo "update-initramfs: Generating ${initramfs}"
 	OPTS="-o"
 	if [ "${verbose}" = 1 ]; then
-		OPTS="-v $OPTS"
+		OPTS="-v ${OPTS}"
 	fi
-	if mkinitramfs ${OPTS} "${initramfs}" "${version}"; then
+	if mkinitramfs ${OPTS} "${initramfs}.new" "${version}"; then
+		mv -f "${initramfs}.new" "${initramfs}"
 		set_sha1
 	else
 		mkinitramfs_return="$?"
+		remove_initramfs
+		rm -f "${initramfs}.new"
 		if [ "$mkinitramfs_return" = "2" ]; then
 			# minversion wasn't met, exit 0
 			exit 0
 		fi
-		verbose "mkinitramfs failed for ${initramfs}"
+		echo "update-initramfs: failed for ${initramfs}"
 		exit $mkinitramfs_return
 	fi
 }
 
-# only run lilo if no grub is around
+# lilo call
+run_lilo()
+{
+	# show lilo errors on failure
+	if ! lilo -t  > /dev/null 2>&1 ; then
+		echo "ERROR lilo fails for new ${initramfs}:"
+		echo
+		lilo -t
+	fi
+	lilo
+}
+
+# check if lilo is on mbr
+mbr_check()
+{
+	# try to discover grub and be happy
+	[ -r /boot/grub/menu.lst ] \
+		&& groot=$(awk '/^root/{print substr($2, 2, 3); exit}' \
+			/boot/grub/menu.lst)
+	[ -e /boot/grub/device.map ] && [ -n "${groot}" ] \
+		&& dev=$(awk "/${groot}/{ print \$NF}" /boot/grub/device.map)
+	[ -n "${dev}" ] && [ -r ${dev} ] \
+		&& dd if="${dev}" bs=512 skip=0 count=1 2> /dev/null \
+		| grep -q GRUB && return 0
+
+	# check out lilo.conf for validity
+	boot=$(awk -F = '/^boot=/{ print $2}' /etc/lilo.conf)
+	[ -z "${boot}" ] && return 0
+	case ${boot} in
+	/dev/md/*)
+		if [ -r /proc/mdstat ]; then
+			MD=${boot#/dev/md/}
+			boot="/dev/$(awk "/^md${MD}/{print substr(\$5, 1, 3)}" \
+			/proc/mdstat)"
+		fi
+		;;
+	/dev/md*)
+		if [ -r /proc/mdstat ]; then
+			MD=${boot#/dev/}
+			boot="/dev/$(awk "/^${MD}/{print substr(\$5, 1, 3)}" \
+			/proc/mdstat)"
+		fi
+		;;
+	esac
+	[ ! -r "${boot}" ] && return 0
+	dd if="${boot}" bs=512 skip=0 count=1 2> /dev/null | grep -q LILO \
+		&& run_lilo && return 0
+
+	# no idea which bootloader is used
+	echo
+	echo "WARNING: grub and lilo installed."
+	echo "If you use grub as bootloader everything is fine."
+	echo "If you use lilo as bootloader you must run lilo!"
+	echo
+}
+
+# Invoke bootloader
 run_bootloader()
 {
-	if [ -x /sbin/grub -o -e /boot/grub/menu.lst ]; then
-		if [ -e /etc/lilo.conf ]; then
-			echo
-			echo "WARNING: grub and lilo installed."
-			echo "If you use grub as bootloader everything is fine."
-			echo "If you use lilo as bootloader you must run lilo!"
-			echo
+	# if both lilo and grub around, figure out if lilo needs to be run
+	if [ -x /sbin/grub ] || [ -e /boot/grub/menu.lst ] \
+	|| [ -x /usr/sbin/grub ]; then
+		if [ -e /etc/lilo.conf ] && [ -x /sbin/lilo ]; then
+			[ -r "${KPKGCONF}" ] && \
+			do_b=$(awk  '/^do_bootloader/{print $3}' "${KPKGCONF}")
+			if [ "${do_b}" = "yes" ] || [ "${do_b}" = "Yes" ] \
+				|| [ "${do_b}" = "YES" ]; then
+				run_lilo
+				return 0
+			elif [ "${do_b}" = "no" ] || [ "${do_b}" = "No" ] \
+				|| [ "${do_b}" = "NO" ]; then
+				return 0
+			else
+				mbr_check
+				return 0
+			fi
 		fi
 		return 0
 	fi
-	if [ -e /etc/lilo.conf ]; then
-		lilo -t > /dev/null
-		if [ $? -eq 0 ]; then
-			lilo
-		fi
+	if [ -r /etc/lilo.conf ] && [ -x /sbin/lilo ]; then
+		run_lilo
+		return 0
+	fi
+	if [ -x /sbin/elilo ]; then
+		elilo
+		return 0
+	fi
+	if [ -r /etc/zipl.conf ]; then
+		zipl
+	fi
+	if flash-kernel --supported >/dev/null 2>&1; then
+		flash-kernel
+	fi
+	if glantank-update-kernel --supported >/dev/null 2>&1; then
+		glantank-update-kernel
 	fi
 }
 
@@ -117,6 +285,23 @@ set_sha1()
 delete_sha1()
 {
 	rm -f "${STATEDIR}/${version}"
+}
+
+# ro /boot is not modified
+ro_boot_check()
+{
+	# check irrelevant inside of a chroot
+	if [ ! -r /proc/mounts ] || chrooted; then
+		return 0
+	fi
+
+	boot_opts=$(awk '/boot/{if ((match($4, /^ro/) || match($4, /,ro/)) \
+		&& $2 == "/boot") print "ro"}' /proc/mounts)
+	if [ -n "${boot_opts}" ]; then
+		echo "WARNING: /boot is ro mounted."
+		echo "update-initramfs: Not updating ${initramfs}"
+		exit 0
+	fi
 }
 
 get_sorted_versions()
@@ -173,7 +358,7 @@ set_linked_version()
 set_highest_version()
 {
 	get_sorted_versions
-	set - ${version_list}
+	set -- ${version_list}
 	version=${1}
 }
 
@@ -189,7 +374,7 @@ create()
 		if version_exists "${version}"; then
 			panic "Cannot create version ${version}: already exists"
 		fi
-	
+
 		if [ -e "${initramfs}" ]; then
 			panic "${initramfs} already exists, cannot create."
 		fi
@@ -200,6 +385,11 @@ create()
 
 update()
 {
+	if [ "${update_initramfs}" = "no" ]; then
+		echo "update-initramfs: Not updating initramfs."
+		exit 0
+	fi
+
 	if [ -z "${version}" ]; then
 		set_linked_version
 	fi
@@ -217,33 +407,19 @@ update()
 		exit 0
 	fi
 
-	if [ "${version}" = "all" ]; then
-		: FIXME check for --yes, and if not ask are you sure
-		get_sorted_versions
-		if [ -z "${version_list}" ]; then
-			verbose "Nothing to do, exiting."
-			exit 0
-		fi
-		for u_version in ${version_list}; do
-			if [ "${verbose}" = "1" ]; then
-				vflag="-v"
-			fi
-			# Don't stop if one version doesn't work.
-			set +e
-			"${0}" -u -k "${u_version}" ${vflag}
-			set -e
-		done
-		exit 0
-	fi
-
 	set_initramfs
 
+	ro_boot_check
+
 	altered_check
+
+	backup_initramfs
 
 	generate_initramfs
 
 	run_bootloader
 
+	backup_booted_initramfs
 }
 
 delete()
@@ -257,26 +433,31 @@ delete()
 	if [ ! -e "${initramfs}" ]; then
 		panic "Cannot delete ${initramfs}, doesn't exist."
 	fi
-	
+
 	if ! version_exists "${version}"; then
 		panic "Cannot delete version ${version}: Not created by this utility."
 	fi
 
 	altered_check
 
+	echo "update-initramfs: Deleting ${initramfs}"
+
 	delete_sha1
 
 	rm -f "${initramfs}"
 }
 
-
+# Check for update mode on existing and modified initramfs
 altered_check()
 {
-	if [ "${takeover}" = 0 ]; then
-		if ! compare_sha1; then
-			delete_sha1
-			mild_panic "${initramfs} has been altered.  Cannot update."
-		fi
+	# No check on takeover
+	[ "${takeover}" = 1 ] && return 0
+	if [ ! -e "${initramfs}" ]; then
+		mild_panic "${initramfs} does not exist. Cannot update."
+	fi
+	if ! compare_sha1; then
+		echo "update-initramfs: ${initramfs} has been altered." >&2
+		mild_panic "update-initramfs: Cannot update. Override with -t option."
 	fi
 }
 
@@ -284,14 +465,14 @@ altered_check()
 verbose=0
 yes=0
 # We default to takeover=1 in Ubuntu, but not Debian
-takeover=1
+takeover=0
 
 ##
 
 while getopts "k:cudyvtb:h?" flag; do
 	case "${flag}" in
 	k)
-		version="${OPTARG}"	
+		version="${OPTARG}"
 		;;
 	c)
 		mode="c"
@@ -325,10 +506,39 @@ while getopts "k:cudyvtb:h?" flag; do
 done
 
 # Validate arguments
-
 if [ -z "${mode}" ]; then
 	usage "You must specify at least one of -c, -u, or -d."
 fi
+
+if [ "${version}" = "all" ] \
+	|| ( [ "${update_initramfs}" = "all" ] && [ -z "${version}" ] ); then
+	: FIXME check for --yes, and if not ask are you sure
+	get_sorted_versions
+	if [ -z "${version_list}" ]; then
+		verbose "Nothing to do, exiting."
+		exit 0
+	fi
+
+	OPTS="-b ${BOOTDIR}"
+	if [ "${verbose}" = "1" ]; then
+		OPTS="${OPTS} -v"
+	fi
+	if [ "${takeover}" = "1" ]; then
+		OPTS="${OPTS} -t"
+	fi
+	if [ "${yes}" = "1" ]; then
+		OPTS="${OPTS} -y"
+	fi
+	for u_version in ${version_list}; do
+		# Don't stop if one version doesn't work.
+		set +e
+		verbose "Execute: ${0} -${mode} -k \"${u_version}\" ${OPTS}"
+		"${0}" -${mode} -k "${u_version}" ${OPTS}
+		set -e
+	done
+	exit 0
+fi
+
 
 case "${mode}" in
 	c)
@@ -341,5 +551,3 @@ case "${mode}" in
 		update
 		;;
 esac
-
-
