0.92bubuntu1 (patches unapplied)
Imported using git-ubuntu import.

diff --git a/update-initramfs b/update-initramfs
--- a/update-initramfs
+++ b/update-initramfs
@@ -5,21 +5,23 @@ BOOTDIR=/boot
 CONF=/etc/initramfs-tools/update-initramfs.conf
 KPKGCONF=/etc/kernel-img.conf
 USETRIGGERS=true
+mode=""
+version=""
 
 set -e
 
 [ -r ${CONF} ] && . ${CONF}
 
 if	   $USETRIGGERS						\
-	&& test x"$DPKG_MAINTSCRIPT_PACKAGE" != x		\
-	&& test $# = 1						\
-	&& test x"$1" = x-u					\
+	&& [ x"$DPKG_MAINTSCRIPT_PACKAGE" != x ]		\
+	&& [ $# = 1 ]	 					\
+	&& [ x"$1" = x-u ]					\
 	&& dpkg-trigger --check-supported 2>/dev/null
 then
 	if dpkg-trigger --no-await update-initramfs; then
 		echo "update-initramfs: deferring update (trigger activated)"
 		exit 0
-	fi	
+	fi
 fi
 
 usage()
@@ -42,6 +44,19 @@ Options:
 
 EOF
 	exit 1
+}
+
+# chroot check
+chrooted()
+{
+        # borrowed from udev's postinst
+        if [ "$(stat -c %d/%i /)" = "$(stat -Lc %d/%i /proc/1/root 2>/dev/null)" ]; then
+                # the devicenumber/inode pair of / is the same as that of
+                # /sbin/init's root, so we're *not* in a chroot and hence
+                # return false.
+                return 1
+        fi
+        return 0
 }
 
 mild_panic()
@@ -85,7 +100,8 @@ backup_initramfs()
 	[ ! -r "${initramfs}" ] && return 0
 	initramfs_bak="${initramfs}.dpkg-bak"
 	[ -r "${initramfs_bak}" ] && rm -f "${initramfs_bak}"
-	ln -f "${initramfs}" "${initramfs_bak}" || cp -a "${initramfs}" "${initramfs_bak}"
+	ln -f "${initramfs}" "${initramfs_bak}" \
+		|| cp -a "${initramfs}" "${initramfs_bak}"
 	verbose "Keeping ${initramfs_bak}"
 }
 
@@ -97,7 +113,7 @@ backup_booted_initramfs()
 	# first time run thus no backup
 	[ ! -r "${initramfs_bak}" ] && return 0
 
-	# chroot
+	# chroot with no /proc
 	[ ! -r /proc/uptime ] && rm -f "${initramfs_bak}" && return 0
 
 	# no kept backup wanted
@@ -124,12 +140,12 @@ backup_booted_initramfs()
 	rm -f ${initramfs_bak}
 }
 
-# restore initramfs backup
-restore_initramfs()
+# nuke generated copy
+remove_initramfs()
 {
 	[ -z "${initramfs_bak}" ] && return 0
 	rm -f "${initramfs_bak}"
-	verbose "Restoring ${initramfs_bak}"
+	verbose "Removing ${initramfs_bak}"
 }
 
 
@@ -145,7 +161,7 @@ generate_initramfs()
 		set_sha1
 	else
 		mkinitramfs_return="$?"
-		restore_initramfs
+		remove_initramfs
 		rm -f "${initramfs}.new"
 		if [ "$mkinitramfs_return" = "2" ]; then
 			# minversion wasn't met, exit 0
@@ -161,7 +177,7 @@ run_lilo()
 {
 	# show lilo errors on failure
 	if ! lilo -t  > /dev/null 2>&1 ; then
-		echo "update-initramfs: lilo run failed for ${initramfs}:"
+		echo "ERROR lilo fails for new ${initramfs}:"
 		echo
 		lilo -t
 	fi
@@ -171,10 +187,27 @@ run_lilo()
 # check if lilo is on mbr
 mbr_check()
 {
+	# try to discover grub and be happy
+	[ -r /boot/grub/menu.lst ] \
+		&& groot=$(awk '/^root/{print substr($2, 2, 3); exit}' \
+			/boot/grub/menu.lst)
+	[ -e /boot/grub/device.map ] && [ -n "${groot}" ] \
+		&& dev=$(awk "/${groot}/{ print \$NF}" /boot/grub/device.map)
+	[ -n "${dev}" ] && [ -r ${dev} ] \
+		&& dd if="${dev}" bs=512 skip=0 count=1 2> /dev/null \
+		| grep -q GRUB && return 0
+
 	# check out lilo.conf for validity
 	boot=$(awk -F = '/^boot=/{ print $2}' /etc/lilo.conf)
 	[ -z "${boot}" ] && return 0
 	case ${boot} in
+	/dev/md/*)
+		if [ -r /proc/mdstat ]; then
+			MD=${boot#/dev/md/}
+			boot="/dev/$(awk "/^md${MD}/{print substr(\$5, 1, 3)}" \
+			/proc/mdstat)"
+		fi
+		;;
 	/dev/md*)
 		if [ -r /proc/mdstat ]; then
 			MD=${boot#/dev/}
@@ -187,16 +220,6 @@ mbr_check()
 	dd if="${boot}" bs=512 skip=0 count=1 2> /dev/null | grep -q LILO \
 		&& run_lilo && return 0
 
-	# try to discover grub and be happy
-	[ -r /boot/grub/menu.lst ] \
-		&& groot=$(awk '/^root/{print substr($2, 2, 3); exit}' \
-			/boot/grub/menu.lst)
-	[ -e /boot/grub/device.map ] && [ -n "${groot}" ] \
-		&& dev=$(awk "/${groot}/{ print \$NF}" /boot/grub/device.map)
-	[ -n "${dev}" ] && [ -r ${dev} ] \
-		&& dd if="${dev}" bs=512 skip=0 count=1 2> /dev/null \
-		| grep -q GRUB && return 0
-	
 	# no idea which bootloader is used
 	echo
 	echo "WARNING: grub and lilo installed."
@@ -261,8 +284,13 @@ delete_sha1()
 # ro /boot is not modified
 ro_boot_check()
 {
-	[ -r /proc/mounts ] || return 0
-	boot_opts=$(awk '/boot/{if (match($4, /(.*,|^)ro(,.*|$)/) && $2 == "/boot") print "ro"}' /proc/mounts)
+	# check irrelevant inside of a chroot
+	if [ ! -r /proc/mounts ] || chrooted; then
+		return 0
+	fi
+
+	boot_opts=$(awk '/boot/{if ((match($4, /^ro/) || match($4, /,ro/)) \
+		&& $2 == "/boot") print "ro"}' /proc/mounts)
 	if [ -n "${boot_opts}" ]; then
 		echo "WARNING: /boot is ro mounted."
 		echo "update-initramfs: Not updating ${initramfs}"
@@ -422,7 +450,8 @@ altered_check()
 		mild_panic "${initramfs} does not exist. Cannot update."
 	fi
 	if ! compare_sha1; then
-		mild_panic "${initramfs} has been altered. Cannot update."
+		echo "update-initramfs: ${initramfs} has been altered." >&2
+		mild_panic "update-initramfs: Cannot update. Override with -t option."
 	fi
 }
 
@@ -475,7 +504,8 @@ if [ -z "${mode}" ]; then
 	usage "You must specify at least one of -c, -u, or -d."
 fi
 
-if [ "${version}" = "all" ]; then
+if [ "${version}" = "all" ] \
+	|| ( [ "${update_initramfs}" = "all" ] && [ -z "${version}" ] ); then
 	: FIXME check for --yes, and if not ask are you sure
 	get_sorted_versions
 	if [ -z "${version_list}" ]; then
@@ -502,6 +532,7 @@ if [ "${version}" = "all" ]; then
 	done
 	exit 0
 fi
+
 
 case "${mode}" in
 	c)
