0.99 (patches unapplied)
Imported using git-ubuntu import.

diff --git a/update-initramfs b/update-initramfs
--- a/update-initramfs
+++ b/update-initramfs
@@ -3,7 +3,6 @@
 STATEDIR=/var/lib/initramfs-tools
 BOOTDIR=/boot
 CONF=/etc/initramfs-tools/update-initramfs.conf
-KPKGCONF=/etc/kernel-img.conf
 USETRIGGERS=true
 mode=""
 version=""
@@ -14,17 +13,28 @@ set -e
 
 [ -r ${CONF} ] && . ${CONF}
 
-if	   $USETRIGGERS						\
-	&& [ x"${DPKG_MAINTSCRIPT_PACKAGE:-}" != x ]		\
-	&& [ $# = 1 ]	 					\
-	&& [ x"$1" = x-u ]					\
-	&& dpkg-trigger --check-supported 2>/dev/null
-then
-	if dpkg-trigger --no-await update-initramfs; then
-		echo "update-initramfs: deferring update (trigger activated)"
+case "$DPKG_MAINTSCRIPT_PACKAGE" in
+linux-image-*)
+	if [ -z "$INITRAMFS_TOOLS_KERNEL_HOOK" ]; then
+		# kernel maintainer script called us directly; ignore
+		# it and let the hook script handle it instead
+		echo "update-initramfs: deferring update (hook will be called later)"
 		exit 0
 	fi
-fi
+	;;
+?*)
+	if	   $USETRIGGERS						\
+		&& [ $# = 1 ]						\
+		&& [ x"$1" = x-u ]					\
+		&& dpkg-trigger --check-supported 2>/dev/null
+	then
+		if dpkg-trigger --no-await update-initramfs; then
+			echo "update-initramfs: deferring update (trigger activated)"
+			exit 0
+		fi
+	fi
+	;;
+esac
 
 usage()
 {
@@ -170,7 +180,7 @@ generate_initramfs()
 			# minversion wasn't met, exit 0
 			exit 0
 		fi
-		echo "update-initramfs: failed for ${initramfs}" >&2
+		echo "update-initramfs: failed for ${initramfs} with $mkinitramfs_return." >&2
 		exit $mkinitramfs_return
 	fi
 }
@@ -197,41 +207,7 @@ run_bootloader()
 		return 0
 	fi
 
-	# FIXME: to be removed postsqueeze release
-	# if both lilo and grub around, figure out if lilo needs to be run
-	if ( command -v update-grub >/dev/null 2>&1 \
-		|| [ -e /boot/grub/menu.lst ] || [ -e /boot/grub/grub.cfg ] ) \
-	&& ( [ -e /etc/lilo.conf ] && command -v lilo >/dev/null 2>&1 ); then
-		[ -r "${KPKGCONF}" ] && \
-		do_b=$(awk  '/^do_bootloader/{print $3}' "${KPKGCONF}")
-		if [ "${do_b}" = "yes" ] || [ "${do_b}" = "Yes" ] \
-		|| [ "${do_b}" = "YES" ]; then
-			run_lilo
-			return 0
-		elif [ "${do_b}" = "no" ] || [ "${do_b}" = "No" ] \
-		|| [ "${do_b}" = "NO" ]; then
-			return 0
-		fi
-
-		# do_bootloader unconfigured
-		echo
-		echo "WARNING: grub and lilo installed."
-		echo "Please deinstall unused bootloader."
-		echo
-		return 0
-	fi
-	if [ -r /etc/lilo.conf ] && command -v lilo >/dev/null 2>&1; then
-		run_lilo
-		return 0
-	fi
-	if [ -r /etc/elilo.conf ] && command -v elilo >/dev/null 2>&1; then
-		elilo
-		return 0
-	fi
-	if [ -r /etc/zipl.conf ]; then
-		zipl
-		return 0
-	fi
+	# FIXME: to be removed once flash-kernel installs a hook
 	if flash-kernel --supported >/dev/null 2>&1; then
 		flash-kernel ${version}
 		return 0
