0.125ubuntu1 (patches unapplied)
Imported using git-ubuntu import.

diff --git a/scripts/functions b/scripts/functions
--- a/scripts/functions
+++ b/scripts/functions
@@ -31,6 +31,42 @@ log_end_msg()
 	_log_msg "done.\n"
 }
 
+# Add failure hook
+add_mountroot_fail_hook()
+{
+	mkdir -p /tmp/mountroot-fail-hooks.d
+	ln -s "$0" /tmp/mountroot-fail-hooks.d/"$1"
+}
+
+# Run failure hooks.
+# When a failure hook exits "1", it has not done anything to correct the
+# system.  Exiting "0" means that something has been attempted to resolve
+# the lack of a root filesystem.
+# Hooks are run in lexigraphical order, and are responsible for removing
+# themselves if they should not re-run in a later cycle.  When one exits
+# "0", the stack is stopped, so the caller can return to the main rootfs
+# wait loop.
+try_failure_hooks()
+{
+	local hook
+
+	# Disable usplash so text from hooks can be seen
+	if [ -x /sbin/usplash_write ]; then
+		/sbin/usplash_write "QUIT"
+	fi
+	chvt 1
+	if [ -x /bin/plymouth ] && plymouth --ping; then
+		/bin/plymouth hide-splash > /dev/null 2>&1
+	fi
+
+	for hook in /tmp/mountroot-fail-hooks.d/*; do
+		if [ -x ${hook} ] && ${hook} mountfail; then
+			return 0
+		fi
+	done
+	return 1
+}
+
 panic()
 {
 	local console rest
@@ -318,10 +354,44 @@ read_fstab_entry() {
 # Resolved name is echoed.
 resolve_device() {
 	DEV="$1"
+	local orig="$DEV"
 
 	case "$DEV" in
 	LABEL=* | UUID=* | PARTLABEL=* | PARTUUID=*)
-		DEV="$(blkid -l -t "$DEV" -o device)" || return 1
+		DEV="$(blkid -l -t "$DEV" -o device)"
+		if [ "$?" != 0 ]; then
+			DEV="$orig"
+
+			# Support uppercase and lowercase UUIDs -- see RFC#4122:
+			#   "Each field is treated as an integer and has its value printed as
+			#    a zero-filled hexadecimal digit string with the most significant
+			#    digit first.  The hexadecimal values "a" through "f" are output as
+			#    lower case characters and are case insensitive on input."
+			#
+			# Note: that blkid which we will use to map these assums the input is lower
+			# case.
+
+			# Only apply this behaviour to UUIDs.
+			case "$DEV" in
+			UUID=* | PARTUUID=*)	;;
+			*)			return 1 ;;
+			esac
+
+			# Pull DEV appart and map it.
+			local type=$(echo ${DEV} | cut -f 1 -d =)
+			local value=$(echo ${DEV} | cut -f 2 -d = | tr '[A-F]' '[a-f]')
+
+			# ... in RFC#4122 format;
+			# look for five hexadecimal fragments separated by minus signs.
+			local fmt=$( echo "$value" | sed -e 's/[0-9a-fA-F]*//g' )
+			if [ "$fmt" != '----' ]; then
+				return 1
+			fi
+			DEV="${type}=${value}"
+
+			# Retry with the lower cased UUID.
+			DEV="$(blkid -l -t "$DEV" -o device)" || return 1
+		fi
 		;;
 	esac
 	[ -e "$DEV" ] && echo "$DEV"
