0.125ubuntu11 (patches unapplied)
Imported using git-ubuntu import.

diff --git a/scripts/functions b/scripts/functions
--- a/scripts/functions
+++ b/scripts/functions
@@ -385,6 +385,55 @@ configure_networking()
 			break
 		fi
 	done
+
+	netinfo_to_resolv_conf /etc/resolv.conf \
+		/run/net-${DEVICE}.conf /run/net-*.conf /run/net6-*.conf
+}
+
+netinfo_to_resolv_conf() {
+	# netinfo_to_resolv_conf(output, files)
+	# write resolv_conf from /run/net-<device> style files.
+	if [ "${_in_subshell:-0}" = "0" ]; then
+		# subshell to avoid modification of variables by '.'
+		( _in_subshell=1; netinfo_to_resolv_conf "$@" )
+		return
+	fi
+
+	local output="$1" search="" ns="" f="" n=""
+	shift
+	{
+	for f in "$@"; do
+		[ -f "$f" ] || continue
+		unset IPV4DNS0 IPV4DNS1 IPV6DNS0 IPV6DNS1
+		unset DOMAINSEARCH IPV6DOMAINSEARCH
+		. "$f" || { echo "WARN: failed '. \"$f\"'" 1>&2; return 1; }
+		for n in "${IPV4DNS0}" "${IPV4DNS1}" \
+			"${IPV6DNS0}" "${IPV6DNS1}"; do
+			[ -n "$n" -a "$n" != "0.0.0.0" ] || continue
+			# skip if 'n' already in list.
+			case " ${ns} " in
+				*\ $n\ *) continue;;
+			esac
+			ns="${ns} ${n}"
+		done
+		for n in "${DOMAINSEARCH}" "${IPV6DOMAINSEARCH}"; do
+			[ -n "$n" ] || continue
+			# skip if already in search.
+			case " ${search}" in
+				*\ $n\ *) continue;;
+			esac
+			search="$search $n"
+		done
+		search=${search# }
+		ns=${ns# }
+	done
+	for n in ${ns}; do
+		echo "nameserver $n"
+	done
+	if [ -n "${search}" ]; then
+		echo "search ${search}"
+	fi
+	} > "$output"
 }
 
 # Wait for queued kernel/udev events
