0.131ubuntu1 (patches unapplied)
Imported using git-ubuntu import.

diff --git a/scripts/functions b/scripts/functions
--- a/scripts/functions
+++ b/scripts/functions
@@ -31,6 +31,42 @@ log_end_msg()
 	_log_msg "done.\n"
 }
 
+# Add failure hook
+add_mountroot_fail_hook()
+{
+	mkdir -p /tmp/mountroot-fail-hooks.d
+	ln -s "$0" /tmp/mountroot-fail-hooks.d/"$1"
+}
+
+# Run failure hooks.
+# When a failure hook exits "1", it has not done anything to correct the
+# system.  Exiting "0" means that something has been attempted to resolve
+# the lack of a root filesystem.
+# Hooks are run in lexigraphical order, and are responsible for removing
+# themselves if they should not re-run in a later cycle.  When one exits
+# "0", the stack is stopped, so the caller can return to the main rootfs
+# wait loop.
+try_failure_hooks()
+{
+	local hook
+
+	# Disable usplash so text from hooks can be seen
+	if [ -x /sbin/usplash_write ]; then
+		/sbin/usplash_write "QUIT"
+	fi
+	chvt 1
+	if [ -x /bin/plymouth ] && plymouth --ping; then
+		/bin/plymouth hide-splash > /dev/null 2>&1
+	fi
+
+	for hook in /tmp/mountroot-fail-hooks.d/*; do
+		if [ -x ${hook} ] && ${hook} mountfail; then
+			return 0
+		fi
+	done
+	return 1
+}
+
 panic()
 {
 	local console rest
@@ -180,6 +216,34 @@ get_fstype ()
 	return ${RET}
 }
 
+all_netbootable_devices()
+{
+	for device in /sys/class/net/* ; do
+		if [ ! -e $device/flags ]; then
+			continue
+		fi
+
+		loop=$(($(cat $device/flags) & 0x8 && 1 || 0))
+		bc=$(($(cat $device/flags) & 0x2 && 1 || 0))
+		ptp=$(($(cat $device/flags) & 0x10 && 1 || 0))
+
+		# Skip any device that is a loopback
+		if [ $loop = 1 ]; then
+			continue
+		fi
+
+		# Skip any device that isn't a broadcast
+		# or point-to-point.
+		if [ $bc = 0 ] && [ $ptp = 0 ]; then
+			continue
+		fi
+
+		DEVICE="$DEVICE $(basename $device)"
+	done
+
+	echo $DEVICE
+}
+
 configure_networking()
 {
 	if [ -n "${BOOTIF}" ]; then
@@ -212,14 +276,12 @@ configure_networking()
 				current_mac=$(cat "$device/address")
 				if [ "$bootif_mac" = "$current_mac" ]; then
 					DEVICE=${device##*/}
+					DEVICE6=${device##*/}
 					break
 				fi
 			fi
 		done
 	fi
-
-	# networking already configured thus bail out
-	[ -n "${DEVICE}" ] && [ -e /run/net-"${DEVICE}".conf ] && return 0
 
 	wait_for_udev 10
 
@@ -233,12 +295,29 @@ configure_networking()
 		# Ip-Config tries to create this file and when it succeds
 		# creating the file, ipconfig is not run again.
 		for x in /run/net-"${DEVICE}".conf /run/net-*.conf ; do
-			[ -e "$x" ] && break 2
+			if [ -e "$x" ]; then
+				IP=done
+				break
+			fi
 		done
 
+		for x in /run/net6-"${DEVICE}".conf /run/net6-*.conf ; do
+			if [ -e "$x" ]; then
+				IP6=done
+				break
+			fi
+		done
+
+		# if we've reached a point where both IP and IP6 are "done",
+		# then we're finished with network configuration.
+		if [ "$IP" = done ] && [ "$IP6" = done ]; then
+			break
+		fi
+
 		case ${IP} in
-		none|off)
+		none|done|off)
 			# Do nothing
+			IP=done
 			;;
 		""|on|any)
 			# Bring up device
@@ -263,17 +342,276 @@ configure_networking()
 			fi
 			;;
 		esac
+
+		case ${IP6} in
+		""|none|done|off)
+			# Do nothing
+			IP6=done
+			;;
+		*)
+			# if this is not the first loop, sleep to provide the backoff.
+			[ "$(($ROUNDTTT-2))" = "0" ] || sleep $ROUNDTTT
+
+			# check the content of IP6, if we have something other
+			# than a device name there and BOOTIF isn't set, clear
+			# DEVICE6 and we'll try all available devices.
+			if echo "${IP6}" | grep -v '^\(on\|dhcp\|any\)$'; then
+				DEVICE6="$IP6"
+			fi
+
+			# if we don't have a device specified, try to bring up
+			# any eligible device.
+			if [ -z "${DEVICE6}" ]; then
+				DEVICE6=$(all_netbootable_devices)
+			fi
+
+			# Bring up device
+			for dev in ${DEVICE6} ; do
+				dhclient -6 -1 -v "${dev}"
+			done
+
+			DEVICE6=$dev
+			;;
+		esac
 	done
 
-	# source ipconfig output
-	if [ -n "${DEVICE}" ]; then
-		# source specific bootdevice
-		. /run/net-${DEVICE}.conf
-	else
-		# source any interface...
-		# ipconfig should have quit after first response
-		. /run/net-*.conf
+	# source ipconfig output for either $DEVICE or the first one.
+	# If the user is booting with only IPv6, then DEVICE may be set,
+	# but no IPv4 conf files exist.
+	for conf in /run/net-${DEVICE}.conf /run/net-*.conf; do
+		if [ -e "${conf}" ]; then
+			# source specific bootdevice
+			. ${conf}
+			break
+		fi
+	done
+
+	netinfo_to_resolv_conf /etc/resolv.conf \
+		/run/net-${DEVICE}.conf /run/net-*.conf /run/net6-*.conf
+	netinfo_to_netplan /run/netplan \
+		/run/net-${DEVICE}.conf /run/net-*.conf /run/net6-*.conf
+}
+
+netinfo_to_resolv_conf() {
+	# netinfo_to_resolv_conf(output, files)
+	# write resolv_conf from /run/net-<device> style files.
+	if [ "${_in_subshell:-0}" = "0" ]; then
+		# subshell to avoid modification of variables by '.'
+		( _in_subshell=1; netinfo_to_resolv_conf "$@" )
+		return
 	fi
+	local output="$1" search="" ns="" f="" n=""
+	shift
+	for f in "$@"; do
+		[ -f "$f" ] || continue
+		unset IPV4DNS0 IPV4DNS1 IPV6DNS0 IPV6DNS1
+		unset DOMAINSEARCH IPV6DOMAINSEARCH
+		. "$f" || { echo "WARN: failed '. \"$f\"'" 1>&2; return 1; }
+		for n in "${IPV4DNS0}" "${IPV4DNS1}" \
+			"${IPV6DNS0}" "${IPV6DNS1}"; do
+			[ -n "$n" -a "$n" != "0.0.0.0" ] || continue
+			# skip if 'n' already in list.
+			case " ${ns} " in
+				*\ $n\ *) continue;;
+			esac
+			ns="${ns} ${n}"
+		done
+		for n in "${DOMAINSEARCH}" "${IPV6DOMAINSEARCH}"; do
+			[ -n "$n" ] || continue
+			# skip if already in search.
+			case " ${search}" in
+				*\ $n\ *) continue;;
+			esac
+			search="$search $n"
+		done
+		search=${search# }
+		ns=${ns# }
+	done
+
+	local rconf="" CR="
+"
+	for n in ${ns}; do
+		rconf="${rconf}nameserver $n${CR}"
+	done
+	if [ -n "${search}" ]; then
+		rconf="${rconf}search ${search}${CR}"
+	fi
+	if [ -z "$rconf" ]; then
+		echo "no search or nameservers found in $*" 1>&2
+	fi
+	if [ "$rconf" = "-" ]; then
+		echo -n "$rconf"
+	else
+		echo -n "$rconf" > "$output"
+	fi
+}
+
+mask2cidr() {
+	# https://forum.openwrt.org/viewtopic.php?pid=220781#p220781
+	# Assumes there's no "255." after a non-255 byte in the mask
+	local x=${1##*255.}
+	set -- 0^^^128^192^224^240^248^252^254^ $(( (${#1} - ${#x})*2 )) ${x%%.*}
+	x=${1%%$3*}
+	echo $(( $2 + (${#x}/4) ))
+}
+
+_declare_sh_append_var() {
+	# append_var(name, skip, strings)
+	# write a declaration of name that will append to any existing
+	local name="$1" skip="$2" add="" n=""
+	shift 2
+	for n in "$@"; do
+		[ -n "$n" -a "$n" != "$skip" ] || continue
+		add="$add $n"
+	done
+	add=${add# }
+	[ -n "$add" ] || return 0
+	echo "$name=\"\${${name}:+\${${name}} }${add}\""
+}
+
+_declare_ip_info() {
+	# declare_ip_info(version, proto, address, netmask, gateway)
+	local version="$1" proto="$2" address="$3" netmask="$4" gateway="$5"
+	local netprefix=""
+	if [ "$proto" = "dhcp" -o "$proto" = "dhcp4" -o "$proto" = "dhcp6" ]; then
+		echo "dhcp${version}=true"
+	elif [ "$proto" = "static" ]; then
+		if [ -n "$address" ]; then
+			netprefix=$netmask
+			if [ "$version" = "4" ]; then
+				netprefix=$(mask2cidr "$netmask")
+			fi
+			_declare_sh_append_var addresses "" "$address/$netprefix"
+		fi
+		if [ -n "$gateway" ]; then
+			echo "gateway${version}=$gateway"
+		fi
+	fi
+}
+
+_render_netplan() {
+	# write a netplan stanza for the given device.
+	local name="$1" mac="$2" dhcp4="$3" dhcp6="$4" addrs="$5" \
+		gateway4="$6" gateway6="$7" ns_addrs="$8" ns_search="$9"
+	local n found=""
+	echo "network:"
+	echo "  version: 2"
+	echo "  renderer: networkd"
+	echo "  ethernets:"
+	echo "    $name:"
+	if [ -n "$mac" ]; then
+		echo "      match:"
+		echo "        macaddress: \"$mac\""
+		echo "      set-name: $name"
+	fi
+	if [ -n "$dhcp4" ]; then
+		echo "      dhcp4: $dhcp4"
+		echo "      dhcp-identifier: mac"
+	fi
+	[ -n "$dhcp6" ] && echo "      dhcp6: $dhcp6"
+	( [ -n "$dhcp4" ] || [ -n "$dhcp6" ] ) && echo "      critical: true"
+	if [ -n "$addrs" ]; then
+		echo "      addresses:"
+		found=","
+		for n in $addrs; do
+			# remove dups
+			[ "${found#*,$n,}" = "${found}" ] || continue
+			found="${found}$n,"
+			echo "        - \"$n\""
+		done
+	fi
+	[ -n "$gateway4" ] && echo "      gateway4: \"$gateway4\""
+	[ -n "$gateway6" ] && echo "      gateway6: \"$gateway6\""
+
+	if [ -n "$ns_addrs" ]; then
+		local alist="[" slist=""
+		for n in $ns_addrs; do
+			# do not put in duplicates
+			[ "${alist#*\"$n\"}" = "$alist" ] || continue
+			alist="${alist}\"$n\", ";
+		done
+		alist="${alist%, }]"
+
+		if [ -n "$ns_search" ]; then
+			slist="["
+			for n in ${ns_search}; do
+				# do not put in duplicates
+				[ "${slist#*\"$n\"}" = "$slist" ] || continue
+				slist="${slist}\"$n\", ";
+			done
+			slist="${slist%, }]"
+		fi
+		echo "      nameservers:"
+		echo "        addresses: $alist"
+		[ -n "$slist" ] && echo "        search: $slist"
+	fi
+}
+
+netinfo_to_netplan() {
+	# read /run/net-* files write netplan config.
+	if [ "${_in_subshell:-0}" = "0" ]; then
+		# subshell to avoid modification of variables by '.'
+		( _in_subshell=1; netinfo_to_netplan "$@" )
+		return
+	fi
+	local out_d="$1" tmpd
+	if command -v mktemp >/dev/null 2>&1; then
+		tmpd=$(mktemp -d "${TMPDIR:-/tmp}/${0##*/}.XXXXXX")
+	else
+		tmpd="${TMPDIR:-/tmp}/${0##*/}.niinfo.$$"
+		mkdir -p "$tmpd" || return
+	fi
+
+	local devices="" pre="" mac=""
+	# we go through all the files presented and create per-device files in
+	# a tmpdir that are shell sourceable and closer to the netplan that
+	# we want to render. Then render those to netplan stanzas.
+	for f in "$@"; do
+		[ -f "$f" ] || continue
+		unset DEVICE DEVICE6 PROTO IPV6PROTO
+		unset IPV6ADDR IPV6NETMASK IPV6GATEWAY
+		unset IPV4ADDR IPV4NETMASK IPV4GATEWAY
+		. "$f" || { echo "WARN: failed '. \"$f\"'" 1>&2; return 1; }
+		local name=""
+		name=${DEVICE:-${DEVICE6}}
+		[ -n "$name" ] || {
+			echo "WARN: $f did not define DEVICE or DEVICE6" 1>&2;
+			return 1;
+		}
+		case " ${devices} " in
+			*\ ${name}\ *) :;;
+			*) devices="${devices} ${name}"
+		esac
+		if [ ! -e "$tmpd/$name" -a -r "/sys/class/net/$name/address" ]; then
+			read mac < /sys/class/net/$name/address &&
+				echo "macaddress=$mac" > "$tmpd/$name"
+		fi
+
+		{
+		if [ -n "$DEVICE" ]; then
+			_declare_ip_info 4 "$PROTO" "$IPV4ADDR" "$IPV4NETMASK" "$IPV4GATEWAY"
+		elif [ -n "$DEVICE6" ]; then
+			_declare_ip_info 6 "$IPV6PROTO" "$IPV6ADDR" "$IPV6NETMASK" \
+				"$IPV6GATEWAY"
+		fi
+		_declare_sh_append_var ns_addresses "0.0.0.0" \
+			"${IPV4DNS0}" "${IPV4DNS1}" "${IPV6DNS0}" "${IPV6DNS1}"
+		_declare_sh_append_var ns_search "" "$DOMAINSEARCH" "$IPV6DOMAINSEARCH"
+		} >> "$tmpd/$name"
+	done
+
+	[ -d "$out_d" ] || mkdir -p "$out_d" ||
+		{ echo "WARN: failed mkdir $out_d"; return 1; }
+
+	for name in $devices; do
+		local macaddress="" dhcp4="" dhcp6="" addresses=""
+		local gateway4="" gateway6="" ns_addresses="" ns_search=""
+		. "$tmpd/$name"
+		_render_netplan "$name" "$macaddress" "$dhcp4" "$dhcp6" "$addresses" \
+			"$gateway4" "$gateway6" "$ns_addresses" "$ns_search" \
+			> "${out_d}/$name.yaml"
+	done
+	rm -Rf "$tmpd"
 }
 
 # Wait for queued kernel/udev events
@@ -318,10 +656,44 @@ read_fstab_entry() {
 # Resolved name is echoed.
 resolve_device() {
 	DEV="$1"
+	local orig="$DEV"
 
 	case "$DEV" in
 	LABEL=* | UUID=* | PARTLABEL=* | PARTUUID=*)
-		DEV="$(blkid -l -t "$DEV" -o device)" || return 1
+		DEV="$(blkid -l -t "$DEV" -o device)"
+		if [ "$?" != 0 ]; then
+			DEV="$orig"
+
+			# Support uppercase and lowercase UUIDs -- see RFC#4122:
+			#   "Each field is treated as an integer and has its value printed as
+			#    a zero-filled hexadecimal digit string with the most significant
+			#    digit first.  The hexadecimal values "a" through "f" are output as
+			#    lower case characters and are case insensitive on input."
+			#
+			# Note: that blkid which we will use to map these assums the input is lower
+			# case.
+
+			# Only apply this behaviour to UUIDs.
+			case "$DEV" in
+			UUID=* | PARTUUID=*)	;;
+			*)			return 1 ;;
+			esac
+
+			# Pull DEV appart and map it.
+			local type=$(echo ${DEV} | cut -f 1 -d =)
+			local value=$(echo ${DEV} | cut -f 2 -d = | tr '[A-F]' '[a-f]')
+
+			# ... in RFC#4122 format;
+			# look for five hexadecimal fragments separated by minus signs.
+			local fmt=$( echo "$value" | sed -e 's/[0-9a-fA-F]*//g' )
+			if [ "$fmt" != '----' ]; then
+				return 1
+			fi
+			DEV="${type}=${value}"
+
+			# Retry with the lower cased UUID.
+			DEV="$(blkid -l -t "$DEV" -o device)" || return 1
+		fi
 		;;
 	esac
 	[ -e "$DEV" ] && echo "$DEV"
