0.120ubuntu1 (patches unapplied)
Imported using git-ubuntu import.

diff --git a/scripts/local b/scripts/local
--- a/scripts/local
+++ b/scripts/local
@@ -42,52 +42,40 @@ local_bottom()
 # $2=optionname (for root and etc)
 local_device_setup()
 {
-	wait_for_udev 10
-
-	# Load ubi with the correct MTD partition and return since fstype
-	# doesn't work with a char device like ubi.
-	if [ -n "$UBIMTD" ]; then
-		modprobe ubi mtd=$UBIMTD
-		return
-	fi
-
 	# Don't wait for a root device that doesn't have a corresponding
 	# device in /dev (ie, mtd0)
 	if [ "${1#/dev}" = "$1" ]; then
 		return
 	fi
 
-	# If the root device hasn't shown up yet, give it a little while
-	# to allow for asynchronous device discovery (e.g. USB).  We
-	# also need to keep invoking the local-block scripts in case
-	# there are devices stacked on top of those.
-	if [ ! -e "$1" ] || ! $(get_fstype "$1" >/dev/null); then
-		log_begin_msg "Waiting for $2 file system"
+	while [ -z "${FSTYPE}" ]; do
+		case $DPKG_ARCH in
+			powerpc|ppc64|ppc64el)
+				ARCHDELAY=180
+				;;
+			*)
+				ARCHDELAY=30
+				;;
+		esac
+		FSTYPE=$(wait-for-root "${1}" ${ROOTDELAY:-$ARCHDELAY})
 
-		# Timeout is max(30, rootdelay) seconds (approximately)
-		slumber=30
-		if [ ${ROOTDELAY:-0} -gt $slumber ]; then
-			slumber=$ROOTDELAY
+		# Load ubi with the correct MTD partition and return since
+		# fstype doesn't work with a char device like ubi.
+		if [ -n "$UBIMTD" ]; then
+			modprobe ubi mtd=$UBIMTD
+			return
 		fi
 
-		while true; do
-			sleep 1
-			local_block "$1"
-			if [ -e "$1" ] && get_fstype "$1" >/dev/null; then
-				wait_for_udev 10
-				log_end_msg 0
-				break
-			fi
-			slumber=$(( ${slumber} - 1 ))
-			if [ ${slumber} -eq 0 ]; then
-				log_end_msg 1 || true
-				break
-			fi
-		done
-	fi
+		# Run failure hooks, hoping one of them can fix up the system
+		# and we can restart the wait loop.  If they all fail, abort
+		# and move on to the panic handler and shell.
+		if [ -z "${FSTYPE}" ] && ! try_failure_hooks; then
+			break
+		fi
+	done
 
 	# We've given up, but we'll let the user fix matters if they can
-	while [ ! -e "$1" ]; do
+	while [ -z "${FSTYPE}" -a ! -e "$1" ]; do
 		# give hint about renamed root
 		case "$1" in
 		/dev/hd*)
@@ -126,7 +114,8 @@ local_mount_root()
 
 	# Get the root filesystem type if not set
 	if [ -z "${ROOTFSTYPE}" ]; then
-		FSTYPE=$(get_fstype "${ROOT}")
+		[ -n "${FSTYPE}" ] || FSTYPE=$(blkid -s TYPE -o value "${ROOT}")
+		ROOTFSTYPE="${FSTYPE}"
 	else
 		FSTYPE=${ROOTFSTYPE}
 	fi
@@ -135,23 +124,72 @@ local_mount_root()
 
 	ROOT=$(resolve_device "$ROOT")
 
-	if [ "${readonly}" = "y" ]; then
+	if [ "${readonly}" = "y" ] && \
+	   [ -z "$LOOP" ]; then
 		roflag=-r
 	else
 		roflag=-w
 	fi
 
 	# FIXME This has no error checking
-	modprobe ${FSTYPE}
+	[ -n "${FSTYPE}" ] && modprobe ${FSTYPE}
 
 	checkfs ${ROOT} root
 
 	# FIXME This has no error checking
 	# Mount root
-	if [ "${FSTYPE}" != "unknown" ]; then
-		mount ${roflag} -t ${FSTYPE} ${ROOTFLAGS} ${ROOT} ${rootmnt}
-	else
-		mount ${roflag} ${ROOTFLAGS} ${ROOT} ${rootmnt}
+	mount ${roflag} ${FSTYPE:+-t ${FSTYPE} }${ROOTFLAGS} ${ROOT} ${rootmnt}
+	mountroot_status="$?"
+	if [ "$LOOP" ]; then
+		if [ "$mountroot_status" != 0 ]; then
+			if [ ${FSTYPE} = ntfs ] || [ ${FSTYPE} = vfat ]; then
+				panic "
+Could not mount the partition ${ROOT}.
+This could also happen if the file system is not clean because of an operating
+system crash, an interrupted boot process, an improper shutdown, or unplugging
+of a removable device without first unmounting or ejecting it.  To fix this,
+simply reboot into Windows, let it fully start, log in, run 'chkdsk /r', then
+gracefully shut down and reboot back into Windows. After this you should be
+able to reboot again and resume the installation.
+(filesystem = ${FSTYPE}, error code = $mountroot_status)
+"
+			fi
+		fi
+	
+		mkdir -p /host
+		mount -o move ${rootmnt} /host
+
+		while [ ! -e "/host/${LOOP#/}" ]; do
+			panic "ALERT!  /host/${LOOP#/} does not exist.  Dropping to a shell!"
+		done
+
+		# Get the loop filesystem type if not set
+		if [ -z "${LOOPFSTYPE}" ]; then
+			eval $(fstype < "/host/${LOOP#/}")
+		else
+			FSTYPE="${LOOPFSTYPE}"
+		fi
+		if [ "$FSTYPE" = "unknown" ] && [ -x /sbin/blkid ]; then
+			FSTYPE=$(/sbin/blkid -s TYPE -o value "/host/${LOOP#/}")
+			[ -z "$FSTYPE" ] && FSTYPE="unknown"
+		fi
+
+		if [ ${readonly} = y ]; then
+			roflag=-r
+		else
+			roflag=-w
+		fi
+
+		# FIXME This has no error checking
+		modprobe loop
+		modprobe ${FSTYPE}
+
+		# FIXME This has no error checking
+		mount ${roflag} -o loop -t ${FSTYPE} ${LOOPFLAGS} "/host/${LOOP#/}" ${rootmnt}
+
+		if [ -d ${rootmnt}/host ]; then
+			mount -o move /host ${rootmnt}/host
+		fi
 	fi
 }
 
